- nodemon.json
- vite.config.ts
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/8
> Add source map build config

- utils/plugins/custom-dynamic-import.ts
- vite.config.ts
add custom dynamic import plugin to fix the issues below
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/23
> Add custom dynamic import plugin

- package.json
- utils/reload/initReloadClient.ts
- utils/reload/initReloadServer.ts
- yarn.lock
Hi, thanks you for this awesome template. It helped me a lot.
I found some issues while developing on windows, these are my fixes, I hope you find them useful
**npm run build**
- "&" is not compatible on windows, replaced with cross platform "npm-run-all"
**Fixes hot-reload**
- normalize paths "\\" to "/"
- fixes debounce code (the method returned by debounce must be called outside of the scope)
- add log messages
> fixes hot-reload on Windows

- utils/plugins/make-manifest.ts
Reverts Jonghakseo/chrome-extension-boilerplate-react-vite#44
> Revert "Fix: make-manifest outDir path"

- utils/plugins/custom-dynamic-import.ts
Reverts Jonghakseo/chrome-extension-boilerplate-react-vite#73
HMR is not working
> Revert "fix: custom-dynamic-import now working for import with then"

- package.json
- yarn.lock
Reverts Jonghakseo/chrome-extension-boilerplate-react-vite#78
> Revert "Bump vite and @vitejs/plugin-react"

- utils/reload/initReloadClient.ts
> add: wss close message

- utils/log.ts
I decide to create it more strict, for better dev experience, IMHO string could be every think in that case :)
And I remove default values, cause it's unnecessary here, because you have 'default' in switch case.
> Change color type, to more strict

- README.md
#180 Edit a little description from this issue and it's better right now :)
> improve README description

- package.json
add --mode development when dev env
> issue #191

- .all-contributorsrc
- README.md
- https://github.com/all-contributors/all-contributors
> attatch all-contributors

- utils/reload/initReloadServer.ts
> fix/breaking view scripts on code reload for Windows

- utils/plugins/make-manifest.ts
Fixed https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/266#issuecomment-1806860750
> fix: windows dynamic import protocol issue

- README.md
- manifest.js
- package.json
- pnpm-lock.yaml
- src/pages/sidepanel/SidePanel.css
- src/pages/sidepanel/SidePanel.tsx
- src/pages/sidepanel/index.css
- src/pages/sidepanel/index.html
- src/pages/sidepanel/index.tsx
- vite.config.ts
> feat: add side panel

- README.md
I also see prettier was run on this file and restructure a little ;)
> fix: typo on pages/popup section

- utils/plugins/make-manifest.ts
- utils/plugins/watch-rebuild.ts
- vite.config.ts
The bug(#294) was caused by #280
fixed: #294
> fix: cache invalidation bug

- .husky/commit-msg
- .husky/pre-commit
close https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/341
> fix: use pnpm in husky

- manifest.js
close https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/342
> fix: nodejs experimental warning

- manifest.js
> fix typo to generate Content Script in correct path

- package.json
- pnpm-lock.yaml
- utils/reload/rollup.config.mjs
Comparison   6.5s     →    0.3s 
Official reminder：
> feat(blog): rollup packaging speed optimization

- utils/plugins/add-hmr.ts
- utils/vite.ts
- vite.config.ts
- Extract boilerplate's custom plugins
- Inline some constants
> [Refactor] vite.config.ts

- src/pages/devtools/index.html
- src/pages/newtab/index.html
- src/pages/options/index.html
- src/pages/panel/index.html
- src/pages/popup/index.html
- src/pages/sidepanel/index.html
ref: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/411
> feat: change document lang to en

- README.md
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/456#issuecomment-2106232234
> Fix: issue #456

- chrome-extension/manifest.js
I was fixed 2 permission errors for Firefox, as i see firefox don't support that side panels :)
> fix/firefox side panel errors on Firefox

- packages/hmr/lib/plugins/make-entry-point-plugin.ts
> fix: firefox dev content script dynamic imports

- .gitignore
- chrome-extension/lib/background/index.ts
[refactor: extract chrome-extension from apps](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/commit/20d3edc4b6e542d5b939a12c4a575e81aaee26d0)
> chore: update .gitignore and log message

- .github/workflows/lint.yml
- packages/dev-utils/.eslintignore
- packages/shared/.eslintignore
- packages/shared/lib/hooks/useStorage.tsx
- packages/storage/.eslintignore
> [FIx] Lint Error

- packages/hmr/lib/injections/reload.ts
- packages/hmr/tsconfig.build.json
- packages/hmr/tsconfig.json
> Add chrome types into hmr package

- chrome-extension/vite.config.mts
- packages/hmr/lib/plugins/index.ts
- packages/hmr/lib/plugins/watch-public-plugin.ts
- packages/hmr/package.json
- pnpm-lock.yaml
- Added a new plugin watch-public-plugin under packages/hmr.
- Integrated watchPublicPlugin in chrome-extension's Vite configuration.
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/50035229/1f9c3db4-edae-4797-a2a2-8911f465c47a
> feat: add watchPublicPlugin for Chrome extension #542

- package.json
- pnpm-lock.yaml
solving #521
For the time this package don't supporting higher version, i suggest to downgrade
> fix: downgrade ts version to 5.4 for solve conflict with @typescript-eslint/typescript-estree

- pages/content-ui/src/index.tsx
> Fix: issue#539

- package.json
- pnpm-lock.yaml
> feat: update deps and resolve deps issue

- .github/workflows/build-zip.yml
- .github/workflows/lint.yml
Clean up the build-zip, lint actions
> Enahcne: github actions

- chrome-extension/manifest.js
- chrome-extension/package.json
- pnpm-lock.yaml
I want to propose a small upgrade, for simplify merging configs in manifest file :)
> chore/upgrade manifest.js merging approach

- packages/shared/lib/hooks/useStorage.tsx
> fix: type infer error

- .gitignore
- pages/content-ui/src/tailwind-output.css
Reverts Jonghakseo/chrome-extension-boilerplate-react-vite#596
fix #600
> Revert "feat: ignore tailwind-output css  #595"

- .github/pull_request_template.md
Add pull request template for contributors.
Create `pull_request_template.md`
> [Enhance] Add pull request template

- package.json
Remove node_modules removal scripts that don't work properly in certain environments.
Eliminated "clean:node_modules" and "clean:install" scripts from package.json
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/594#discussion_r1698570712
> chore: remove clean scripts

- pages/content-runtime/lib/index.ts
- pages/content-runtime/lib/root.tsx
- pages/popup/src/Popup.tsx
Enhance Firefox supports
Add comment when using executeScript in Firefox.... :(
Fix reference error when use import in content-runtime in firefox (it's unnecessary)
> Enhance Firefox support

- README.md
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/562
Added a community section to the `README.md` file, and included something about the Discord server.
https://discord.gg/Nu5Rf8xr
Enjoy the show :)
> [Docs] Add community section into README.md

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
update boilerplate's version
update boilerplate's version to 0.3.0
> bump: update version 0.3.0

- packages/ui/lib/components/Button.tsx
- packages/vite-config/lib/withPageConfig.mjs
- pages/content-ui/package.json
- pages/content-ui/src/app.tsx
- pages/content-ui/tailwind.config.js
- pages/new-tab/src/NewTab.tsx
- pages/options/src/Options.tsx
- pnpm-lock.yaml
Enhance the example code in the content ui package.
- Fixed the default button style
- Added examples of using `storage`, `shared`, and `ui` packages in content-ui
- Adjusted buildDelay (50ms too low)
> Add ContentUI examples

- package.json
Remove duplicated `rimraf` package
As in title
> fix: remove duplicated `rimraf` from root `package.json`

- README.md
Users can read it here, instead of googling and try to find solution :)
Add new instruction to README.md and reword a little
> feat: create instruction to add dep to turbo `package.json` files

- package.json
> bump: pnpm to 9.9.0

- README.md
I want to simplify use case
Read :)
> chore: simplify install deps section for `README`

- .github/workflows/build-zip.yml
- chrome-extension/vite.config.mts
For fix type error
Add Plugin's type assertion
pnpm type-check
> Fix: type error

- README.md
I've wanted to unify it, to have one kind of defining it
I've changed links for sections
Try to use those links
> chore: unify links name for README.md

- README.md
I've fix wrong syntax
In `getting started` README section
> fix: README getting started section

- pnpm-lock.yaml
I've other version of lock file, because of the one of PR from past
I've run `pnpm i`
Let's try to remove it and run `pnpm i` again, and check if you will have the same version, because something wrong happened
> fix: create new version of pnpm-lock.yaml

- packages/ui/README.md
- packages/ui/build.mjs
- packages/ui/package.json
- packages/ui/tsconfig.json
- pnpm-lock.yaml
Add the SHADCN guide that`@rutamstwt` posted to the Discord channel to the README of the UI package.
I tested the guide he posted at a practical level and made any adjustments that needed to be made.
Added the tsc-alias course to the build so that the aliasing entered in tsconfig works properly.
Follow the guide to create and use a Button component!
https://ui.shadcn.com/docs/installation/manual
> Adding shadcn guide to README.md

- pages/devtools-panel/src/Panel.tsx
- pages/new-tab/src/NewTab.tsx
- pages/options/src/Options.tsx
- pages/popup/src/Popup.tsx
- pages/side-panel/src/SidePanel.tsx
I just think we should add a quick link to the homepage, which can quickly locate the repo homepage
Add a redirect link to the GitHub homepage for each app logo.
Click on each app logo, open a new tab in the browser, and point to the GitHub homepage.
none
---
Do I need to add a test for correct link redirection?
> style: add a link on the logo to redirect to the GitHub homepage

- package.json
- pnpm-lock.yaml
I want to simplify it, because i've created it more complicated than it can be, as you can see
I've removed `run-os-script` package and simplify `update-version` script
Run `pnpm update-version 0.2.2`
> chore: simplify update-version package script 

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- tests/e2e/package.json
bump version to 0.3.3
run `pnpm update-version 0.3.3`
> bump: 0.3.3

- README.md
specifiy messages.json location in README.md
specify messages.json location in README.md
> specifiy messages.json location in README.md

- chrome-extension/manifest.js
Fix #807
It occurs from `deepMerge`, so I extract sidePanel config to HoF(withSidePanel) and added comment.
1. Delete withSidePanel
2. Build successfully
3. Disabled SidePanel
> Fix #807 - Extract sidePanel config to withSidePanel

- .gitignore
- chrome-extension/package.json
- package.json
- packages/vite-config/package.json
- pnpm-lock.yaml
As i've described there:
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/720#issuecomment-2365303711
I've removed vite.config.mts.timestamp pattern from `.gitignore` and I've created script for cleaning up all timestamp files
> fix: remove vite.config.mts.timestamp from project

- package.json
- pnpm-lock.yaml
Fix issue during `pnpm dev`
Bump turbo to 2.3.3
> fix: turbo build error by bump turbo to 2.3.3

- .github/ISSUE_TEMPLATE/bug_report.md
Create more user friendly bug_report template for GH issues
I've removed placeholders, because it was annoying to remove it.
It was more complicated to select e.g `Windows` from this array then type `Windows` instead.
Try to open new issue
> feat: edit and extend bug_report.md

- .gitattributes
- README.md
This pull request includes changes to `.gitattributes` and `README.md` to streamline the setup process and ensure consistency in line endings across different operating systems.
Configuration updates:
* [`.gitattributes`](diffhunk://#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR1-R2): Added configuration to automatically handle line endings and ensure consistency across different operating systems.
Documentation improvements:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L72-R78): Simplified the setup instructions by removing steps specific to Windows and ensuring the instructions are clear and concise for all users.
closes #836
> Remove git config instructions from README.md and create .gitattributes file

- chrome-extension/package.json
- package.json
- packages/hmr/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/devtools-panel/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
Reduce redundancy in all package.json
I've remove unnecessary and redundant packages from `package.json` in all modules, necessary one i've moved to main `package.json` and all modules take it from here
Run any script e.g `pnpm dev` to check if everything works fine
> feat/Take packages from root package.json

- .github/workflows/build-zip.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/prettier.yml
Add CI on dev branch PR
Edit github action files: add dev branch
> feat: add ci on dev

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- tests/e2e/package.json
> bump: 0.3.6

- .prettierignore
- packages/env/.eslintignore
Remove .eslintignore from env module 
I've removed .eslintignore file which are missed in #699
> fix: remove .eslintignore from env package

- chrome-extension/manifest.ts
- packages/dev-utils/lib/manifest-parser/impl.ts
> main to dev sync

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/env/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- tests/e2e/package.json
> bump: 0.4.0

- README.md
- chrome-extension/manifest.ts
- package.json
- packages/module-manager/README.md
- packages/module-manager/index.mts
- packages/module-manager/lib/deleteModules.ts
- packages/module-manager/lib/paths.ts
- packages/module-manager/lib/recoverModules.ts
- packages/module-manager/lib/runModuleManager.ts
- packages/module-manager/package.json
- packages/module-manager/tsconfig.json
- packages/ui/README.md
- pages/popup/package.json
- pnpm-lock.yaml
> Add Module manger for opt-out unused pages

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/env/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/module-manager/lib/paths.ts
- packages/module-manager/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- tests/e2e/package.json
> bump: 0.4.1

- packages/ui/README.md
Update ui package README for content-ui + shadcn
Add `:host` selector on global.css example
> Edit ui package README

- README.md
> Fixes readmemd

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/env/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/module-manager/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwind-config/package.json
- packages/tsconfig/package.json
- packages/ui/README.md
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- pnpm-lock.yaml
- tests/e2e/package.json
> docs: fix typo

- packages/ui/README.md
> fix: missing global.css import part on readme

- LICENSE
> chore: bump year in LICENSE

- README.md
I've wanted to remove not current info and add new about recommended IDE configuration.
I've edit Getting started section of README and remove version from React for avoid case of forget to bump version also here and other packages, excluding manifest, don't have version and it should look like this.
> docs: remove info about git configuration refactor a little `Getting started` points and add new with IDE/Editor settings

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
Updated the README  and ISSUE TEMPLATE by including information about [Brie](https://go.briehq.com/github?utm_source=CEB), a tool for capturing screenshots, console errors, and network activity to assist with Chrome extension debugging.  
- Updated the **Community** section in README file and **Screenshots** section in ISSUE TEMPLATE file.
Review the updated README and ISSUE TEMPLATE file to ensure the new content is clear and no errors or typos.
Created the PR as per @PatrykKuniczak in [discord](https://discord.com/channels/1263404974830915637/1269673217711411240/1352381309061693490).
> chore: update readme and bug report to mention brie

- packages/ui/lib/components/ToggleButton.tsx
- packages/ui/lib/global.css
- pages/content-ui/package.json
- pages/content-ui/src/App.tsx
- pages/content-ui/tailwind.config.ts
- pages/devtools-panel/src/index.css
- pages/devtools-panel/src/index.tsx
- pages/devtools-panel/tailwind.config.ts
- pages/new-tab/src/index.css
- pages/new-tab/src/index.tsx
- pages/new-tab/tailwind.config.ts
- pages/options/src/index.css
- pages/options/src/index.tsx
- pages/options/tailwind.config.ts
- pages/popup/src/index.css
- pages/popup/src/index.tsx
- pages/popup/tailwind.config.ts
- pages/side-panel/src/index.css
- pages/side-panel/src/index.tsx
- pages/side-panel/tailwind.config.ts
- pnpm-lock.yaml
I want to fix issue with tailwind and cleanup classes
- I've fixed issue with the lack of withUI() for some pages
- I've fixed issue with overwriting className for <ToggleButton/>
- I've moved all the same props from index.css file from each page, inside global.css and then import it in each index.css
Run `pnpm build` or `pnpm dev`
> fix/tailwind global styles and ToggleButton styles issue 

- packages/ui/README.md
- packages/ui/lib/withUI.ts
- pages/content-ui/src/tailwind-input.css
I need to fix issue forgotten in #931
- I've imported `global.css` for `content-ui` entry css file
- I've updated docs
- Read README.md of `ui` and 
- Run `pnpm dev` or `pnpm build` for check `content-ui`
> fix/update README for `ui` and add import for css for `content-ui`

- .github/workflows/auto-change-prs-branch.yml
> fix/remove `already-exists` section from auto-change-prs-branch

- .github/workflows/auto-change-prs-branch.yml
> chore/add 'on' reopened for change branch workflow

- .github/workflows/build-zip.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/prettier.yml
> fix/change all `on` from `pull_request` to `pull_request_target`

- packages/dev-utils/lib/manifest-parser/impl.ts
- packages/dev-utils/lib/manifest-parser/types.ts
- packages/env/index.mts
- packages/env/lib/types.ts
- packages/hmr/lib/interpreter/index.ts
- packages/hmr/lib/plugins/watch-rebuild-plugin.ts
- packages/hmr/lib/types.ts
- packages/i18n/lib/i18n-prod.ts
- packages/i18n/lib/types.ts
- packages/module-manager/lib/helpers/utils.ts
- packages/module-manager/lib/types.ts
- packages/shared/lib/hooks/use-storage.tsx
- packages/shared/lib/utils/helpers.ts
- packages/shared/lib/utils/types.ts
- packages/storage/lib/base/base.ts
- packages/storage/lib/base/types.ts
- packages/storage/lib/impl/example-theme-storage.ts
- packages/storage/lib/types.ts
I want to unify convention for naming types and interfaces
Add `Type` suffix for types
Add `I` prefix for interfaces
Run `pnpm build` or `pnpm dev` and check if it works
> feat: use `Type` suffix for types and `I` prefix for interfaces

- chrome-extension/package.json
- package.json
- packages/dev-utils/package.json
- packages/env/package.json
- packages/hmr/package.json
- packages/i18n/package.json
- packages/module-manager/package.json
- packages/shared/package.json
- packages/storage/package.json
- packages/tailwindcss-config/package.json
- packages/tsconfig/package.json
- packages/ui/package.json
- packages/vite-config/package.json
- packages/zipper/package.json
- pages/content-runtime/package.json
- pages/content-ui/package.json
- pages/content/package.json
- pages/devtools-panel/package.json
- pages/devtools/package.json
- pages/new-tab/package.json
- pages/options/package.json
- pages/popup/package.json
- pages/side-panel/package.json
- tests/e2e/package.json
I want to bump versions to 0.5.0 before release
I've bumped versions of all package.json
> deps: bump all package.json versions to 0.5.0

- .github/secret_scanning.yml
- .github/workflows/prettier.yml
I want to fix issue with ignoring `pnpm-lock.yaml` for gitguardian and bump prettier workflow.
Bumped actions/checkout to v4
Fixed ignore path of `pnpm-lock.yaml` for `secret_scanning.yaml`
> Release v0.5.1

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/auto_assign.yml
- .github/workflows/prettier.yml
I want to merge #1011 to `main`
#1011
> Release 0.5.2

- pnpm-lock.yaml
Reverts Jonghakseo/chrome-extension-boilerplate-react-vite#1023
> Revert "build(deps): bump tar-fs from 3.0.8 to 3.1.0"
