src/manifest.ts, src/pages/content/index.ts, src/pages/contentView/app.tsx, src/pages/contentView/index.tsx, vite.config.ts
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/7
Chrome extensions don't support modules in content scripts.
Bundling solves this problem, but not in the case of React, which is imported as JSX automatic conversion.
So, I created a tag that brings the 'content view' from the 'content script', and implemented it by bypassing the tag in the form of inserting it into the html.
If there is a better implementation (bundling option or other method, etc.), please suggest it 😄
=> Add content view in content script

src/pages/content/index.ts
=> fix: run content script with type module

utils/plugins/custom-dynamic-import.ts
Fix for #72 
After more research, I've found that the costume Vite plugin `custom-dynamic-import` was the origin of the problem. it looks like sometime Vite adds `.then()` after `__vitePreload` 
This update will make sure the syntax will stay good even if Vite add `.then` at the end
=> fix: custom-dynamic-import now working for import with then

package.json, utils/manifest-parser/index.ts, utils/plugins/custom-dynamic-import.ts
closes #18
It looks like Firefox doesn't support adoptedStyleSheets in the content-script, even using not Shadow DOM, but even Document (probably related to this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1770592)). 
So, regretfully, tailwind should come old way (linking to extension contentStyle) to make it work in FF content script.
IDK is it worth to create workaround to convert and inject twind styles into App.
=> Support Firefox webextension

package.json
This PR is to fix a minor dependency version issue. Tested on Mac M1 with node 18 and 20, when I run `npm install`, I got the following error:
```
chrome-extension-boilerplate-react-vite$ node -v
v18.12.0
chrome-extension-boilerplate-react-vite$ npm -v
8.19.2
chrome-extension-boilerplate-react-vite$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: chrome-extension-boilerplate-react-vite@0.0.1
npm ERR! Found: typescript@4.8.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"4.8.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.8.4" from @twind/preset-autoprefix@1.0.7
npm ERR! node_modules/@twind/preset-autoprefix
npm ERR!   dev …
```
=> Fix peer dependency issue

manifest.js, utils/plugins/make-manifest.ts, utils/plugins/watch-rebuild.ts, utils/reload/initReloadClient.ts, utils/reload/initReloadServer.ts, utils/reload/injections/script.ts, utils/reload/interpreter/types.ts, vite.config.ts
Fixed https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/261
- Modify the manifest.ts file with the js extension
- The make-manifest plugin watches the manifest file and rebuilds it
- Disable emptyOutDir option only in dev
=> [Enhance] modify to detect and reload manifest changes

README.md
fix: #296
Added a short explanation to the README to make it work without CSS.
If you want to clear all contentStyle css related settings, please see the commit below (there may be changes)
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/compare/main...workaround/missing-css-on-content
=> docs: added a guide for deleting css files when they are not used

utils/log.ts
Color should be defined, cause if not, 'undefined' could be used as a index
=> fix: change color type to not be undefined

src/pages/content/ui/index.tsx
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/307
I've added the CSS injection method presented in the above issue as an example case.
This should be useful if someone wants to use CSS inside the shadow DOM.
=> Enhance: add a css insertion case to shadow dom

README.md
the written version on the Readme is not correct. 
source: [Chrome Side Panel Documentation] (https://developer.chrome.com/docs/extensions/reference/api/sidePanel#availability)
=> doc: correct sidepanel chrome version

src/shared/storages/base.ts, src/shared/storages/exampleThemeStorage.ts
Hi thank you for maintaining this boilerplate :) 
I've noticed that `StorageType.Session` wasn't able to be fully utilized, since they need an [extra access-level step](https://developer.chrome.com/docs/extensions/reference/storage/#type-AccessLevel) in chrome to allow content scripts to also access that storage area. A functionality that is pretty important for background workers processing page content.
So I have added that functionality after noticing. 
Also, since the whole browser extension landscape is rather confusing for most people, I have added brief [TSDocs](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) to the `createStorage` interface and proximal types to provide in editor guidance:
----- 
Originally I wanted to extend your creatStorage solution …
=> feat: add session storage access levels, live update across instances + TSDocs IntelliSense for guidance 

src/pages/content/injected.ts, src/shared/storages/exampleThemeStorage.ts
there is a bug in content script, for storage usage example. theme storage toggle failed according to the log in Chrome Devtool
=> fix: theme storage toggle failed in Content script example #338

package.json
`lint-staged` is already configured to lint not just `*.ts` files but also `*.tsx`, `*.js`, and `*.jsx`.  Also `eslint` is already configured with `eslint-plugin-react`.  So make `pnpm lint` run on the same file types for completeness and consistency.
=> fix: include .tsx, .js, and .jsx files in pnpm lint script

package.json, pnpm-lock.yaml, utils/plugins/inline-vite-preload-script.ts
=> Add sourcemap into preload chunk files

src/shared/storages/base.ts
if it's Promise, we can use `.then`, `.catch` and `finally`: 
otherwise, we can't:
Reference: [Using type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)
=> Fix type guard to return the correct type

utils/plugins/make-manifest.ts
Ensure 'forEach' is not called on undefined 'manifest.content_scripts' to prevent the '[make-manifest] Cannot read properties of undefined (reading 'forEach')' error that occurs when the content script section is absent from the manifest.
=> fix: check manifest content scripts existence before iteration

README.md
The rest styling changes has been applied cause, the IDE 
Default line max length :)
=> fix: wrong file name for README.md

src/shared/storages/base.ts
Add support for non trivial types like Date, Object and Array
for example, Date, (timestampStorage.ts):
```
import { BaseStorage, createStorage, StorageType } from '@src/shared/storages/base';
type TimestampStorage = BaseStorage<Date | undefined> & {
mark: () => Promise<void>;
};
const storage = createStorage('timestamp', new Date(), {
storageType: StorageType.Local,
liveUpdate: true,
serialization: {
deserialize: (text: string) => {
return new Date(text);
},
serialize: (value: Date) => {
return value?.toISOString();
},
},
});
export const timestampStorage: TimestampStorage = {
...storage,
mark: async () => {
await storage.set(() => {
return new Date();
});
},
};
```
Usage:
```
const timestamp = useStorage(timestampStorage);
timestamp?.toISOString()
```
=> refactor: add support to non trivial types

utils/plugins/inline-vite-preload-script.ts
When I use the main option, the page variable will conflict with the variable of the plug -in and report an error
The improved packing code is as follows:
=> fix(blog): variable conflict

packages/hmr/package.json, packages/hmr/tsconfig.build.json
fix: node ^20 versions breaking change
- https://github.com/TypeStrong/ts-node/issues/1997
use transpiled `js` file instead of original `ts` file.
=> Fix: issue #454

chrome-extension/package.json, package.json, packages/dev-utils/package.json, packages/hmr/package.json, packages/shared/package.json, packages/storage/package.json, pages/content-ui/package.json, pages/content/package.json, pages/devtools-panel/package.json, pages/devtools/package.json, pages/newtab/package.json, pages/options/package.json, pages/popup/package.json, pages/sidepanel/package.json
fix
- #496
It looks like the removal of 'cache:false' to the turbo folder caused a permission error.
- #492
I think the correct fix is to exclude .turbo from the clean target because when someone rerun the turbo build, they might want to use the cache.
=> Fix: build error on windows

pages/popup/src/Popup.tsx
If we don't need new-tab page and delete it, the popup page will crash like:
Because the logo in the Popup page is used directly from the new-tab page and not its own.
With the fix, the page work alone!
By simply using the existing logo in the Popup folder.
=> Fix logo in the popup page

turbo.json
https://turbo.build/repo/docs/reference/configuration#ui
https://github.com/vercel/turbo/releases/tag/v2.0.6
The default UI has been restored in TurboRepo 2.0.6.
Now, to use TUI, we need to use the settings.
=> Use turborepo tui

chrome-extension/vite.config.mts, pages/content-ui/vite.config.mts, pages/content/vite.config.mts, pages/devtools-panel/vite.config.mts, pages/devtools/vite.config.mts, pages/new-tab/vite.config.mts, pages/options/vite.config.mts, pages/popup/vite.config.mts, pages/side-panel/vite.config.mts
It's necessary because the build folders are located outside root dir
solving #526
=> fix: remove messages about empty directory for all modules

package.json
As we know, pnpm hasn't implement `pnpm clean-install` yet.
https://github.com/pnpm/pnpm/issues/6100
For convenience, add `clean:install` command.
fix #523
=> feat: add 'clean:node_modules' and 'clean:install' commands

packages/storage/build.mjs, packages/storage/lib/base.ts, packages/storage/package.json, packages/vite-config/lib/withPageConfig.mjs
If you use a package like storage in a UI package, for example, you will get a reference error during the build phase.
I found that the chrome reference error occurs during the `processTailwindFeatures` execution of tailwindcss. To avoid this, I look for references to chrome in globlaThis, and add fallback logic.
This is a temporary measure until we have a better way.
=> fix: chrome reference error when use storage in ui package

package.json, packages/dev-utils/lib/manifest-parser/impl.ts, packages/zipper/index.ts, packages/zipper/lib/zip-bundle/index.ts, pages/content-runtime/lib/root.tsx, pages/content-ui/src/index.tsx, pages/devtools/src/index.ts, pages/popup/src/Popup.tsx, turbo.json
Firefox support improvement
I was thinking to add e2e tests for both browsers. For Firefox running in Puppeter extension needs to be zipped and installed.
This PR allows zipping of Firefox extension and cleans Firefox related turbojs scripts
feat: zipped firefox extension ready to work 
fix: zipper bundles on windows with posix slashes
refactor: zip command respects firefox settings
refactor: extension scripts depend on turbojs global firefox environment variable 
turbojs scripts refactoring:
(run `pnpm dev`) check Chrome can load extension (Firefox can't) [chrome://extensions/](chrome://extensions/)
(run `pnpm dev:firefox`) Firefox can load extension (Chrome can't)  [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
zipper work:
(run `pnpm zip`) Chrome …
=> Better firefox support

.husky/pre-commit
Husky v9 now prints a deprecation notice on every commit: 
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
This fixes that according to https://github.com/typicode/husky/releases/tag/v9.0.1
Commits now no longer print the deprecation warning.
=> Fix husky pre-commit giving deprecation notice

package.json
Give users possibility to use ```pnpm clean``` script in 100% :)
Add shut down turbo daemon before rimraf 
run ```pnpm clean```
I was thinking also about total shut down of daemon, but i'm not sure, we're really need it.
@Jonghakseo If we don't need it, we can turn it off globally, but it isn't working properly for now.
I was sent question to turborepo community, let's wait for response :)
https://github.com/vercel/turbo/pull/8728#issuecomment-2275534895
=> fix/not permitted unlink for 'pnpm clean'

packages/storage/build.mjs
Avoid warning displaying.
Also on ```storage``` for 99% .tsx files will not be stored.
Removed ``` './lib/**/*.tsx' ``` from esbuild config
Not necessary
=> fix: remove unused .tsx files pattern from storage/esbuild

packages/tsconfig/base.json
On the #682 i changed this value, because one person from discord suggest it, but it isn't good idea, because i see a part of pages don't work properly, we need to change it immediately.
I removed `module` from `tsconfig`
This it very urgent :)
=> fix: export module error

packages/hmr/lib/initializers/initReloadServer.ts
It's not easy to find error when wss crashed.
Throw error when wss onError
=> pEnhance] add throw when websocket server error

packages/shared/lib/hooks/useStorage.tsx, pages/content-ui/src/app.tsx, pages/devtools-panel/src/Panel.tsx, pages/new-tab/src/NewTab.tsx, pages/options/src/Options.tsx, pages/popup/src/Popup.tsx, pages/side-panel/src/SidePanel.tsx
Users are confused about this `Suspense` prefix, that's because we had 2 identical functions in the past, i want to simplify it :)
I've renamed `useStorageSuspense` to `useStorage`
Use new name instead of old one
=> fix: rename `useStorageSuspense` to `useStorage`

.gitignore
I've done it because of the conversation on Discord, it's annoying we need to remove it everytime.
For fix we need to wait a while:
https://github.com/vitejs/vite/issues/13267
I've added `vite.config.mts.timestamp` files to `.gitignore`
=> fix: add `vite.config.mts.timestamp` files to `.gitignore`

pages/popup/src/Popup.tsx
I haven't tested it on chrome, i'm sure i've done it, but now i see i forgot, sorry
Now icon and entire notification for `chrome` works :)
Try to inject `runtime-script` inside `about:` path on Firefox or `chrome:` on Chrome
=> fix: icon error on injecting notification on chrome

.github/workflows/prettier.yml, chrome-extension/tsconfig.json, package.json, packages/dev-utils/tsconfig.json, packages/hmr/tsconfig.build.json, packages/hmr/tsconfig.json, packages/tsconfig/app.json, packages/ui/tsconfig.json, packages/zipper/tsconfig.json, pages/content-runtime/tsconfig.json, pages/content-ui/tsconfig.json, pages/content/tsconfig.json, pages/devtools-panel/tsconfig.json, pages/devtools/tsconfig.json, pages/new-tab/tsconfig.json, pages/options/tsconfig.json, pages/popup/tsconfig.json, pages/side-panel/tsconfig.json, turbo.json
I've decided to add `json` to `lint-staged` because i've seen there's different version of `tsconfig.json` files in #699 and on my machine, it's because i had set `Reformat code` option in IDE, now i've fixed it, but i want to avoid it in the future by new CI tool, which also could be helpful when somebody unstall `husky` and it doesn't work properly for some reason.
I've add `json` file extension to `lint-staged` and i've created prettier CI
push new commit with inproper file format (check edit history here)
=> chore/create prettier-CI

packages/tsconfig/base.json, pages/devtools-panel/package.json, pages/devtools-panel/postcss.config.ts, pages/new-tab/package.json, pages/new-tab/postcss.config.ts, pages/options/package.json, pages/options/postcss.config.ts, pages/popup/package.json, pages/popup/postcss.config.ts, pages/side-panel/package.json, pages/side-panel/postcss.config.ts
Again #733 but addressed [issue](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/733#issuecomment-2346546612)
- Set module: esnext in base.json
- move all postcss.config.ts to each package.json
PostCss... it works
=> Fix: use module esnext

.github/workflows/build-zip.yml
As i've talked to you, this will be a problem in the future, now is the future :)
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/699#issuecomment-2351124386
I've removed `type-check` from GH CI build action
=> fix: remove `type-check` from GH CI build action

README.md
Background script folder is src/background not lib/background
=> Fix background script path in README.md

packages/i18n/genenrate-i18n.mjs, pnpm-lock.yaml, tests/e2e/config/wdio.browser.conf.ts, tests/e2e/package.json
The tests are passing on stable and beta chrome, but we test on latest canary and looks like that's an issue.
Also noticed small issue with formatting in getMessageFromLocale.ts
Fix failing pipeline, fix eslint/prettier conflicting with generated code
Pipeline tests should be passing
Adding more languages doesn't conflict with prettier formatting in the getMessageFromLocale.ts
=> Rune e2e tests on stable browser release channel

.eslintrc, package.json, pages/content-ui/src/App.tsx, pages/options/src/Options.tsx, pnpm-lock.yaml
This PR adds ESLint with Tailwind CSS support for automatically sorting tailwind classes.
1. Install `eslint-plugin-tailwindcss` as a dev dependency in the root `package.json`.
2. Update root `package.json` with new lint scripts for the entire project.
1. Pull the changes and run `pnpm install` to update dependencies.
2. Run `pnpm run lint` to check if ESLint runs successfully across the entire project.
3. Make a small change that violates a Tailwind CSS rule (e.g., use an invalid class name) in a React component.
4. Run `pnpm run lint` again to verify that the Tailwind CSS linting catches the error.
5. Run `pnpm run lint:fix` to check if auto-fixable issues are corrected.
6. Try running `pnpm dev` and `pnpm build` to ensure the new setup doesn't break existing scripts.
- …
=> Add ESLint plugin with Tailwind CSS support

packages/storage/lib/base/base.ts
Add the inited state and make sure that the callback in the set function can get the correct cache value.
=> Fix set storage before init cache

README.md
Thank you for publishing this boilerplate! As a new user, I was mindful of the onboarding process and I contributed a number of fixes that should help future users get started faster and with more clarity as to what various pars of the boilerplate do.
* explain how to change the extension version
* add warning about restricting permissions to respect users' privacy in production
* clarify `pages` usage
* fix English grammar in sections I had to understand in order to use the boilerplate (this doesn't mean that unchanged sections are correct; just that I didn't get to change them, or that they were too confusing at this stage - see Notes
* update Chrome Extensions URLs (many pointed to `mv3`)
* link pages to their directories
* remove superfluous Markdown section anchors that are generated …
=> docs: improve English, Markdown, and clarity in README

README.md
Solution for #612 + general troubleshooting tips.
Moved the `Pages` section up because it's more important than `Packages` in helping new users understand the structure of the extension.
=> docs: add Troubleshooting section and move Pages up

README.md
In my previous large PR I forgot to add the `VITE_` prefix to accessing the env var via import.meta.env.
https://vite.dev/guide/env-and-mode#env-files
=> docs: fix access to env var using VITE_ prefix in README.md

chrome-extension/manifest.js, chrome-extension/public/refresh.js, chrome-extension/vite.config.mts, packages/hmr/lib/plugins/watch-rebuild-plugin.ts, packages/hmr/lib/types.ts
To fix #796
- Add refresh.js to the public folder for HMR.
- Add refresh.js to manifest, comment it out.
https://github.com/user-attachments/assets/b43ce6d8-4c0d-43ad-b0f4-34ec6e425304
=> [Feat] Support content.css HMR

README.md
It fixed by #799
- Delete content.css trouble shooting section
=> [Docs] Delete content.css troubleshooting section

README.md, package.json, packages/zipper/index.ts, tests/e2e/config/wdio.browser.conf.ts
Inspired by #805, When `pnpm zip` runs, it excludes the `dist-zip` folder from the clean target to leave the existing zip version, and reveals the time of the compression in the filename.
1. exclude dist-zip from clean:bundle.
2. specify compression time in compressed filename.
3. update README.md
=> Enhance: comportable pnpm zip

packages/ui/lib/components/Button.tsx, packages/ui/tsconfig.json
Fix ENOENT error about resolve import "@/lib/utils" 
I've remove alias from `tsconfig` and change import to relative in `Button.tsx`
Run `pnpm dev` or `pnpm build`
=> fix: Vite Rollup error about resolving import with alias

packages/i18n/package.json
I've forgot to remove it in #725
Remove `cross-env` fom `ready:dev` script from`i18n` module package.json
=> hotfix: remove unnecessary `cross-env` from i18n module package.json script

packages/ui/lib/components/Button.tsx, packages/ui/lib/components/ToggleButton.tsx, packages/ui/lib/components/index.ts, packages/ui/lib/index.ts, packages/ui/package.json, pages/content-ui/package.json, pages/content-ui/src/App.tsx, pages/popup/src/Popup.tsx, pnpm-lock.yaml
I want to unify this 2 buttons, because it's strange to toggle theme in e.g `popup` and it doesn't affect `content-ui` button as well
I've create `ToggleButton` which basing on `Button` from `ui` package and use translation for both
Run `pnpm dev` or other and check if it works
=> feat: unify popup and content-ui toggle buttons

pages/content/package.json, pages/content/src/index.ts, pages/content/src/sampleFunction.ts, pages/content/src/toggleTheme.ts, pnpm-lock.yaml
Make sure the theme doesn't change every time the content script is loaded into a page. This can be a bit confusing the first time you test the project.
I removed the `toggleTheme()` function in the content script and the dependency in `package.json`. I added an external function to still show an example of how to define functions in an external module.
Open the extension's side panel and then search in the browser's search bar. The theme no longer changes every time you change pages (when the content script is loaded).
=> Fix: theme toggle each time content script is loaded

turbo.json
=> fix: disable `cache` for turbo `ready` task

packages/shared/index.mts, packages/shared/index.ts, packages/shared/lib/hoc/index.ts, packages/shared/lib/hooks/index.ts, packages/shared/lib/utils/index.ts, packages/shared/package.json, packages/shared/tsconfig.json, packages/storage/index.mts, packages/storage/index.ts, packages/storage/lib/base/base.ts, packages/storage/lib/base/index.ts, packages/storage/lib/base/types.ts, packages/storage/lib/impl/exampleThemeStorage.ts, packages/storage/lib/impl/index.ts, packages/storage/lib/index.ts, packages/storage/package.json, packages/storage/tsconfig.json, packages/ui/README.md, packages/ui/index.mts, packages/ui/index.ts, packages/ui/lib/components/ToggleButton.tsx, packages/ui/lib/components/index.ts, packages/ui/lib/index.ts, packages/ui/lib/withUI.ts, packages/ui/package.json, packages/ui/tsconfig.json
I need to change rest packages to be `module` because it isn't possible to import package(Look on screenshot) which extends `base` tsconfig, because of conflict in `target`, `module`, `moduleResolution` 
I've change extends from `base` to `module` for packages which wasn't had it already and adjust code.
Run `pnpm dev` and check if everything work fine
=> feat: change all packages to be `module`

packages/dev-utils/lib/manifest-parser/impl.ts
Improve handling for making compatible manifest for Firefox when Background Scripts or Options UI are not used in manifest.js 
Add if checks to ensure correct manifest.json for Firefox when `manifest.background?.service_worker` or `manifest.options_page` are undefined
1. Comment or remove `options_page` or `background` in `manifest.js`.
2. Run `pnpm build:firefox`
3. The resultant `dist/manifest.json` will be valid now, which was not the case before
=> Ensure valid manifest for Firefox when background or options are not present

packages/module-manager/lib/recoverModules.ts
The `module-manager` tries to read archive files, but the `archive` dir does not exist in the initial call. 
I changed the `archiveFiles` reader statement to a ternary instead of creating the dir itself since the `deleteModules` already handles dir creation.
1. Delete `packages/module-manager/archive` dir if it exists
2. Run `pnpm module-manager`
Error log:
```
Error: ENOENT: no such file or directory, scandir '{path}/chrome-extension-boilerplate-react-vite/packages/module-manager/archive'
at Object.readdirSync (node:fs:1584:26)
at <anonymous> ({path}/chrome-extension-boilerplate-react-vite/packages/module-manager/lib/recoverModules.ts:9:25)
at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
at async onImport.tracePromise.__proto__ …
```
=> fix(module-manager): read archive files if exists

packages/module-manager/lib/deleteModules.ts, packages/zipper/lib/index.ts
Support converting string chunks to Buffer when streaming files to zip, ensuring consistent data type handling across module-manager and zipper packages
Trying to start the dev server and getting an error ❌
- `packages/module-manager/lib/deleteModules.ts`
-  `packages/zipper/lib/index.ts`
```
pnpm install
pnpm dev
```
Run dev mode Error log:
```
│ lib/index.ts:35:17 - error TS2345: Argument of type '(chunk: Buffer) => void' is not ass
│ ignable to parameter of type '(chunk: string | Buffer<ArrayBufferLike>) => void'.
│   Types of parameters 'chunk' and 'chunk' are incompatible.
│     Type 'string | Buffer<ArrayBufferLike>' is not assignable to type 'Buffer<ArrayBuffe
│ rLike>'.
│       Type 'string' is not assignable to type 'Buffer<ArrayBufferLike>'.
│ 
│ 35 …
```
=> fix: Handle string chunks in file streaming for zip operations

packages/dev-utils/lib/logger.ts, packages/dev-utils/package.json, pnpm-lock.yaml
Use `ValueOf` from shared types instead of redefining it.
=> fix: use `ValueOf` from `@extension/shared` instead of redefining

package.json, packages/dev-utils/package.json, packages/env/package.json, packages/hmr/package.json, packages/i18n/package.json, packages/module-manager/package.json, packages/shared/package.json, packages/storage/package.json, packages/ui/package.json, packages/zipper/package.json, pages/content-runtime/package.json, pages/content-ui/package.json, pages/content/package.json, pages/devtools-panel/package.json, pages/devtools/package.json, pages/new-tab/package.json, pages/options/package.json, pages/popup/package.json, pages/side-panel/package.json, turbo.json
I want to rename it to follow the most common naming convention for this.
I've changed name of script in all package and turbo.json to `format` and add missing ignore flag in one file
Run `pnpm format`
=> chore: rename prettier to format in all package.json

package.json
I've wanted to run eslint with prettier like in GitHub actions, to create one more step of validation, to get know for dev, what's could be wrong with code, before he would decide to open a PR
I've added `eslint --fix` for `lint-staged` in package.json
Add sth to one of the files in project and then try to commit it.
=> fix: add missing eslint --fix for lint-staged

README.md
Update README instructions for setting up VS Code, resolving https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/885 for future users.
Update README.md
1. clone the repo
2. run `pnpm i`
3. open VS Code from WSL directly without the extension, you should see unresolved references in `*.tsx` files
4. install WSL extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
5. run `pnpm i`
6. restart VS Code
7. connect WSL remotely from and open workspace there, references should be resolved.
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/885
=> Update README instructions for setting up VS Code

eslint.config.ts
I want to add 2 more rules to eslint.config.ts
=> feat: add 2 more rules to eslint.config.ts

packages/storage/lib/impl/exampleThemeStorage.ts, packages/ui/lib/components/ToggleButton.tsx, pages/devtools-panel/package.json, pages/devtools-panel/src/Panel.tsx, pages/new-tab/src/NewTab.tsx, pages/options/src/Options.tsx, pages/popup/src/Popup.tsx, pages/side-panel/src/SidePanel.tsx, pnpm-lock.yaml
I want to prettify classNames and simplify checking current theme for classNames
I've changed exampleThemeStorage and use cn() for classNames of components
Run `pnpm build` or `pnpm dev` and check if everything works well
=> feat: prettify classNames in `pages` components

eslint.config.ts
I've added missing rule for checking `type` imports on eslint.config `rules
I've added missing rule for `eslint.config.ts`
Run `pnpm lint` or `pnpm lint:fix`
=> fix: add missing consistent-type-imports rule to eslint.config.ts

eslint.config.ts
I want to add checking imports against import `type-fest` from itself, for avoid redundant imports and import it from the place (`dev-utils`) where it was defined already 
I've configured no-restricted-imports for import `type-fest` values from `@extension/dev-utils` instead.  
- Try to import sth from `type-fest` from package other then `@extension/dev-utils`
- Run `pnpm lint` and check if error will occur
=> feat/configure restriction for importing `type-fest`

.github/workflows/auto-change-prs-branch.yml
It fixes, finally right #946 
I've removed `already-exists-actions` from `auto-change-prs-branch.yml` (workflow)
Like on #946
=> fix/remove closing other actions on branch change(workflow)

README.md
I want to remove it because that API doesn't exist anymore
I've remove that icon from README
Take a look on README.md on root
If you have any other idea, how to implement it(other icon or something) feel free to push here.
=> docs: remove icon next to discord on README.md

packages/shared/const.ts, packages/shared/index.mts, pages/devtools-panel/src/Panel.tsx, pages/new-tab/src/NewTab.tsx, pages/options/src/Options.tsx, pages/popup/src/Popup.tsx, pages/side-panel/src/SidePanel.tsx
I want to simplify `goGithubSite` func for the future, if we decide to change sth in url path, we'll be able to do it in one place.
And it's shorter.
Use `PROJECT_URL_OBJECT` imported from `shared` for `goGithubSite` func in all pages with `ui` 
Run `pnpm dev` and check it works.
=> feat: create project url in shared const and use it across pages

packages/env/index.mts, packages/env/lib/config.ts, packages/env/lib/index.ts
I want to adjust `env` package to export everything necessary from `lib/index.ts` like other packages
I've created `config.ts` for content of previous `index.ts` and export it in current `index.ts`
=> fix: adjust env package to look like other packages

turbo.json
I want to enable daemon again, because it seems `turborepo` fixed issue with daemon and this fixes #827
I've removed `daemon` option from `turbo.json` to use default
=> feat: enable daemon for turbo.json

packages/hmr/package.json
I want to fix issue with starting reload server
I've changed entry point from /dist to directly .ts file with `tsx`, because it wasn't starting well everytime with previous approach
Run `pnpm dev` and check if it works
=> fix: start init-reload-server directly from .ts file

packages/hmr/lib/initializers/init-reload-server.ts
I want to not throw error when HMR trying to reload it self because of e.g `turbo.json` edit
I've added display info about already running server on EADDRINUSE error code for init-reload-server.ts
Run `pnpm dev` and try to edit `turbo.json` and check new info in console.
=> fix: skip throwing error on init-reload-server.ts when server already running

.github/workflows/e2e-modular.yml, .github/workflows/e2e.yml, tests/e2e/specs/page-content-runtime.test.ts
Run tests for separated features
Created `e2e-moduler` GH workflow
1. pnpm module-manager --de tests random-module
2. pnpm run e2e
3. pnpm module-manager -r random-module
4. pnpm run e2e
Closes #937
=> Module manager test
